### ISSUE TITLE
Preboot 4.3 - cannot find module 'preboot' - Ng_preboot (Universal)

### ISSUE THREAD

**Issue by MarkPieszak** [angular/preboot#12]
Preboot 4.3 : from https://github.com/angular/universal-starter/issues/142
(Here for reference)

It works well before updating preboot, after updating preboot to v4.3.0, got error:

module.js:442
throw err;
^

Error: Cannot find module 'preboot'
at Function.Module._resolveFilename (module.js:440:15)
at Function.Module._load (module.js:388:25)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at Object. (/xxx/universal-starter/node_modules/angular2-universal/dist/node/ng_preboot.js:3:16)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
[nodemon] app crashed - waiting for file changes before starting...

-----

It looks like Preboot isn't publishing all the needed files? The d.ts is there, but a lot of things seem missing in dist. Jeff, know you already knew about this, just put it here in case others ran into it!

**Comment by jeffwhelpley** [comment]
This is resolved now. I am working on integration with universal now.
